stages:
  - pages

pages:
  image: registry.gitlab.com/jdriven/jslider/revealjs-template:latest
  stage: pages
  script:
    - mv /public public
    - mv slides public
  artifacts:
    paths:
      - public
